spring.application.name=peak-detector-service
server.port=8084

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Base URL du Usage Collector quand tout est dans Docker
usage.collector.base-url=http://usage-collector-service:8083

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
