apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: smarthome
  labels:
    app: nginx-api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-api-gateway

