spring.application.name=billing-service
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5433/smarthome
spring.datasource.username=smarthome
spring.datasource.password=smarthome
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672


billing.tier1.rate=1.06
billing.tier2.rate=1.22
billing.tier3.rate=1.35
billing.tier4.rate=1.61
billing.subscription=10.00
billing.tax.rate=0.14

logging.level.com.smarthome.billing=INFO
logging.level.org.springframework.amqp=WARN
