spring.application.name=billing-service
server.port=8086

# Postgres (inside docker network)
spring.datasource.url=jdbc:postgresql://postgres:5432/smarthome
spring.datasource.username=smarthome
spring.datasource.password=smarthome
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# optional: remove dialect warning
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ (inside docker network)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
