apiVersion: v1
kind: Service
metadata:
  name: peak-detector-service-nodeport
  namespace: smarthome
  labels:
    app: peak-detector-service
spec:
  type: NodePort
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30084
    protocol: TCP
    name: http
  selector:
    app: peak-detector-service

