apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: smarthome
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: salmaidoufkir/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "http://usage-collector-service:8083"
        - name: USAGE_BASE_URL
          value: "http://usage-collector-service:8083"
        - name: DEVICE_BASE_URL
          value: "http://device-simulator-service:8082"
        - name: PEAK_BASE_URL
          value: "http://peak-detector-service:8084"
        - name: OPTIMIZER_BASE_URL
          value: "http://optimizer-service:8085"
        - name: BILLING_BASE_URL
          value: "http://billing-service:8086"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
      imagePullSecrets:
      - name: registry-secret

