apiVersion: v1
kind: Service
metadata:
  name: usage-collector-service
  namespace: smarthome
  labels:
    app: usage-collector-service
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: usage-collector-service

